# Настройки сайта
title: Общая Теория Макро-ГастроНОМИЧЕСКОГО Континуума
description: Фундаментальная Гидродинамическая Космология и Теория Супа с Сосисками (Версия 4.2)
author: KeelBismark
email: your.email@example.com
lang: ru

# Настройки сборки Jekyll
# Указывает, где искать файлы для сайта (весь репозиторий)
source: ./
destination: ./_site

# Тема (Minima - это минималистичная и академичная тема по умолчанию)
theme: minima

# Включить плагин для GitHub Pages (для корректной обработки ссылок и формул)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Дополнительные настройки (для ссылок)
baseurl: /UTMGC-Official  # ОЧЕНЬ ВАЖНО для корректной работы ссылок на keelbismark.github.io/UTMGC-Official/
markdown: kramdown
highlighter: rouge